### PR TITLE
Added support for reader.deathtollscans.net + scyllascans.org + cosmicscans.com + nightscans.org + nocturnalscans.com & fixed chapter list for omegascans.org

### PR DESCRIPTION
**Pull request by mrstan3772**
### **FOR OMEGASCANS.ORG**
Some titles have several seasons, such as "[The Main Character is the Villain](https://omegascans.org/series/the-main-character-is-the-villain)", so it's impossible to only refer to incomplete page content. I can't simulate click.

### **READER.DEATHTOLLSCANS.NET**
Some titles as "[Island Part 2](https://reader.deathtollscans.net/series/island_part_2/)" have an adult content notice. You need to click on a button to confirm you're old enough. Cookies only work for a limited time. Can you do anything about it?

### CODE REVIEW

**Comment by HDoujinDownloader** [comment]
Really nice work!

> so it's impossible to only refer to incomplete page content

I noticed you read the chapter data from the JSON, which seems to get all chapters from both seasons when I tested it out. I would replace the `GetChapters` function with this, though:

```lua
function GetChapters()

    for chapterJson in GetChaptersJson() do

        local chapterInfo = Json.New(chapterJson)

        if(chapterInfo.SelectValue('price') == '0') then

            local chapterUrl = url:trim('/') .. '/' .. chapterInfo.SelectValue('chapter_slug')
            local chapterTitle = chapterInfo.SelectValue('chapter_name')
            local chapterSubtitle = chapterInfo.SelectValue('chapter_title')
            
            if(chapterSubtitle ~= 'null' and not isempty(chapterSubtitle)) then
                chapterTitle = chapterTitle .. ' - ' .. chapterSubtitle
            end

            chapters.Add(chapterUrl, chapterTitle)
            
        end

    end

end
```
The call to `chapters.Reverse` seems to be obsolete (the chapters were already in order), and I changed the subtitle logic to check for an empty subtitle too. This is because newer versions of HDoujin Downloader just return an empty string instead of  `null`, so this will cover both cases.

> You need to click on a button to confirm you're old enough. Cookies only work for a limited time. Can you do anything about it?

Yes, you can probably just add this site to the `FoolSlide.lua` module instead of creating a separate module for it. There's already logic in there for clicking the button.

**Comment by mrstan3772** [comment]
All right, I'll check for reader.deathtollscans.net.

**Comment by HDoujinDownloader** [comment]
What I meant earlier was that instead of creating a separate module for deathtollscans.net, just add it to the [`FoolSlide.lua`](https://github.com/HDoujinDownloader/HDoujinDownloader/blob/master/modules/lua/FoolSlide.lua) module:

```lua
module.Domains.Add('reader.deathtollscans.net', 'Death Toll Reader')
```
Correct me if I'm wrong, but I think it already covers all the bases (chapter order, cleaning the metadata, etc.). 

After that, I'll accept the merge! ❤️

**Comment by mrstan3772** [comment]
It's done !

**Comment by HDoujinDownloader** [comment]
Beautiful!

**Pull request merged**
