### PR TITLE
Use the native sleep function

### PR DESCRIPTION
**Pull request by ale5000-git**

### CODE REVIEW

**Comment by HDoujinDownloader** [comment]
Good call. ;3

**Comment by ale5000-git** [comment]
@HDoujinDownloader
I use luacheck to check the scripts (this is what pointed me to the invisible characters issues and the sleep thing).

Would it be good if I do some PR to improve consistence?
Currently there are some issues that can be fixed:
- Case inconsistence of string functions (example: startsWith vs startswith) => I suggest all lowercase to keep coherency with standard string functions.
- Case inconsistence of dom and other custom objects functions (dom.selectValue vs dom.SelectValue) => I suggest "SelectValue" to keep coherency with what you use everywhere in your custom objects.
- I can make "local" the functions that are just called by other functions and not by your app (this is very important otherwise luacheck will report everything since it verify global functions).
- I can break lines that are to long to simplify readability in the editor; the value suggested is max 120 characters but we can start with max 182 to reduce the amount of changes (we can still change it later).

Note: 182 is the max I can have on a notebook with LCD 15.6" without have to orizontally scroll the script.

**Comment by HDoujinDownloader** [comment]
Of course, you're welcome to do that if you want; I appreciate it. I realize the documentation is very lacking right now, so that last part is definitely a step in the right direction too. 

I should probably add a style guide to the repository for contributors and take note of these rules. I agree with all of your takes here. The instances of `startsWith` and `selectValue` were completely unintentional. 

I've never mentioned this before, but I used a custom build of MoonSharp with case insensitivity to support FMD's Lua API (the capitalization of which is inconsistent as hell) which has lead to these typos going unnoticed. The majority of FMD modules are also compatible with HDoujin Downloader.

**Comment by mrstan3772** [comment]
It seems that for me, native sleep function didn't give a good result for countdown. But today it doesn't matter, because "Turnstile" issue for this website. So I'm using a controlled browser now.

**Comment by HDoujinDownloader** [comment]
@mrstan3772 The `sleep` function wasn't working right for you? Was its timing too short, or too long? 

The `sleep` function is implemented using `Thread.Sleep`, which guarantees a minimum sleep time with a possible discrepancy of 15-20 milliseconds longer.
```csharp
public static void Sleep(int milliseconds) {

        if (milliseconds <= 0)
                return;

        Thread.Sleep(TimeSpan.FromMilliseconds(milliseconds));

}
 ```
If it's behaving unexpectedly, let me know.

**Comment by mrstan3772** [comment]
> @mrstan3772 The `sleep` function wasn't working right for you? Was its timing too short, or too long?
> 
> The `sleep` function is implemented using `Thread.Sleep`, which guarantees a minimum sleep time with a possible discrepancy of 15-20 milliseconds longer.
> 
> ```cs
> public static void Sleep(int milliseconds) {
> 
>         if (milliseconds <= 0)
>                 return;
> 
>         Thread.Sleep(TimeSpan.FromMilliseconds(milliseconds));
> 
> }
> ```
> 
> If it's behaving unexpectedly, let me know.

This was probably due to pagination  failure link system to dynamically generate corresponding page chapters. Even now, pagination link system is useless except for the first page, where it works correctly. For index beyond that, it's random. I know I had to wait a while to get chapters, but I didn't have right chapters. I can't remember exactly why in the loop the timer wasn't working as expected for me.

**Pull request merged**
