### PR TITLE
Added support for coolmic.me

### PR DESCRIPTION
**Pull request by mrstan3772**
# Missing Login Functionality + Bug Fix + Code Improvement

## LOGIN FUNCTIONALITY

Login procedure exists but is not working yet. We need to find a way to stop returning the [Error 422](https://developer.mozilla.org/en-US/docs/web/http/status/422). 

**POST LOGIN FORM DATA STRUCTURE**

```
authenticity_token: <authenticity_token>
recaptcha_token: <recaptcha_token>
email: <email>
password: <password>
remember: <true | false>
```

Unfortunately I haven't yet found out how **``recaptcha_token``** key value is generated. 

## BUG FIX

Only one chapter can be downloaded at a time, as cookies don't seem to refresh. Page informations are returned with tokens which are necessary to avoid a 403 error.

```
global.SetCookie('.' .. module.Domains.First(), "CloudFront-Policy", signedCookies.SelectValue('CloudFront-Policy'))
global.SetCookie('.' .. module.Domains.First(), "CloudFront-Signature", signedCookies.SelectValue('CloudFront-Signature'))
global.SetCookie('.' .. module.Domains.First(), "CloudFront-Key-Pair-Id", signedCookies.SelectValue('CloudFront-Key-Pair-Id'))
```

Is necessary to change their values for each resource which access has been granted via API.

## CODE IMPROVEMENT

Some code pieces can be modified and optimized. 

I've used ``:contains('true')`` and ``:contains('false')``. I couldn't find equality or format wasn't a compliant string.

_For now, the only real difficulty is login system, but I haven't tried it for very long because I don't really know how to use this program for that. Everything else can easily be fixed._

🤝🙏👊

### CODE REVIEW

**Comment by HDoujinDownloader** [comment]
Very nice work with this so far!

> Unfortunately I haven't yet found out how recaptcha_token key value is generated.

You won't be able to generate a passable value for `recaptcha_token` unfortunately. This is generated in the background by reCAPTCHA v3 based on various heuristics. It's not hopeless though; I'm currently working on a browser-based login method that will help with this.

> Only one chapter can be downloaded at a time, as cookies don't seem to refresh

You might be able to get around this by using them as [query parameters](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-creating-signed-url-custom-policy.html) instead of cookies. The image URLs will look something like:

    https://en-contents.coolmic.me/episodes/XXX/XXXXXX/XXXXXXXXX/XXXXXXXXX-001.jpg?Policy=XXX&Signature=XXX&Key-Pair-Id=XXX

This did the trick on my end.

> I've used :contains('true') and :contains('false')

This is fine. You could also use `toboolean` on the values, but that's more a matter of preference than anything.

**Comment by mrstan3772** [comment]
> You won't be able to generate a passable value for recaptcha_token unfortunately. This is generated in the background by reCAPTCHA v3 based on various heuristics. It's not hopeless though; I'm currently working on a browser-based login method that will help with this.

To import a user session with cookies ?

> You might be able to get around this by using them as [query parameters](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-creating-signed-url-custom-policy.html) instead of cookies. The image URLs will look something like:

Ok, I didn't quite understand protection system for Amazon CloudFront content delivery.

> This is fine. You could also use toboolean on the values, but that's more a matter of preference than anything.

👍

**Comment by OhgunGit** [comment]
> You won't be able to generate a passable value for `recaptcha_token` unfortunately. This is generated in the background by reCAPTCHA v3 based on various heuristics. It's not hopeless though; I'm currently working on a browser-based login method that will help with this.

Would you like for me to test that login method before you release it?

**Comment by HDoujinDownloader** [comment]
> Would you like for me to test that login method before you release it?

I'm going to release it for everyone in a bit. I haven't tested it for Coolmic specifically just yet, but I'm aiming to have it part of the next release.

**Pull request merged**
