### PR TITLE
Added support for imperfectcomic.org, immortalupdates.com, manhwafreak.com, fixed  MadaraAjax module, zeroscan.com and more

### PR DESCRIPTION
**Pull request by mrstan3772**
[Request Concern => #comment-66219](https://doujindownloader.com/comment-page-154/#comment-66219)

### CODE REVIEW

**Comment by mrstan3772** [comment]
[Request Concern => #comment-66284](https://doujindownloader.com/comment-page-154/#comment-66284)

**Comment by mrstan3772** [comment]
### FIXED PAGE LIST DOMAIN

- [hentai20.com](https://hentai20.io/) (to verify => cloudflare challenge)
- [hentaidexy.com](https://hentaidexy.com/)
- [hiperdex.com](https://hiperdex.com/)
- [isekaiscanmanga.com](https://isekaiscanmanga.com/)
- [mangarockteam.com](https://mangarockteam.com/)
- [mangasushi.net](https://mangasushi.org/) (+mangasushi.org)
- [manhuaga.com](https://manhuaga.com/)
- [manhuaplus.com](https://manhuaplus.com/) (some error)
- [manhuaus.com](https://manhuaus.com/manganato-5/)
- [zinmanga.com](https://zinmanga.com/)

More checking needed for **manhuaplus.com**  (error reported `Unexpected MIME type: text/html; charset=utf-8`)

**Error URLs :** 

- https://manhuaplus.com/manga/yuan-zun/
- https://manhuaplus.com/manga/rebirth-of-the-immortal-venerable/
- more



### DEAD LINK / NO DOMAIN

- [kissmanga.link](http://ww1.kissmanga.link/)
- [aloalivn.com](http://ww12.aloalivn.com/)
- [gdegenscans.xyz](https://gdegenscans.xyz/)
- [mangaradar.com](https://megaprogservices.com/)
- [pornwha.com](https://www.hugedomains.com/domain_profile.cfm?d=pornwha.com)

### NO SUPPORT

[earlym.org ](https://earlym.org/home)(earlymanga.net)

**Comment by mrstan3772** [comment]
### ALTERNATIVE SOLUTION

It's seem to work with isekai module but for some domain only. Definitely changes to be made and need more test.

[IsekaiScan.lua](https://github.com/HDoujinDownloader/HDoujinDownloader/blob/master/modules/lua/IsekaiScan.lua)

**Work with :**

- [hentaidexy.com](https://hentaidexy.com/)
- [hiperdex.com](https://hiperdex.com/)
- [mangasushi.net](https://mangasushi.org/) (+mangasushi.org)
- [manhuaga.com](https://manhuaga.com/)
- [immortalupdates.com](https://immortalupdates.com/)
- [manhuaplus.com](https://manhuaplus.com/) (some error)

**Comment by mrstan3772** [comment]
[1666808310.log](https://github.com/HDoujinDownloader/HDoujinDownloader/files/9872679/1666808310.log)
**Link**: https://hiperdex.com/manga/themain-character-is-the-villain/chapter-40/

**Comment by mrstan3772** [comment]
[Request Concern => #comment-66218](https://doujindownloader.com/comment-page-154/#comment-66218)

**Comment by mrstan3772** [comment]
[Request Concern => #comment-66347](https://doujindownloader.com/comment-page-155/#comment-66347)

**Comment by mrstan3772** [comment]
What do this function `DoEncryptedString()` ?

**Comment by HDoujinDownloader** [comment]
Hey, thanks a lot for your contributions! Everything looks pretty good. I'll look over the comments you made and see if I can address some of the issues you ran into.

> What do this function `DoEncryptedString()` ?

It's for executing obfuscated modules. Obfuscating the code is not something I like to do, but sometimes it's necessary to help keep them from breaking so quickly. The downside is, unfortunately, that it makes those modules impossible to contribute to.

**Comment by HDoujinDownloader** [comment]
I uploaded some fixes for **manhuaplus.com** that should address the issues you encountered with it. The direct images were unable to be downloaded without a referrer, so I've now added one. I haven't had the chance to test it thoroughly because FlareSolverr seems to be having issues again, but it should work.

**Pull request merged**
