### PR TITLE
mm-scans.org: fixed chapter list

### PR DESCRIPTION
**Pull request by mrstan3772**

### CODE REVIEW

**Comment by mrstan3772** [comment]
I don't know if it makes sense to leave the leviatanscans module ?

**Comment by HDoujinDownloader** [comment]
> I don't know if it makes sense to leave the leviatanscans module ?

Is there something wrong with LeviatanScans? 

All these changes look good to me, so I'll merge them in. Thanks a lot for your contribution, and sorry for taking so long to review it!

**Comment by mrstan3772** [comment]
> > I don't know if it makes sense to leave the leviatanscans module ?
> 
> Is there something wrong with LeviatanScans?
> 
> All these changes look good to me, so I'll merge them in. Thanks a lot for your contribution, and sorry for taking so long to review it!

I decided to put leviatan's domain names back into its original "IsekaiScan.lua" module. However, I haven't removed its own module.

**Comment by HDoujinDownloader** [comment]
Ah okay, that makes sense. 

Syncing modules doesn't currently delete any that get deleted from the repository, so deleting the module wouldn't affect clients that already have it. I should probably have it remove deleted ones in the future. 👍

I moved the domains back to the "LeviatanScans.lua" module, and now just have it import the "IsekaiScan.lua" module. I left some logic in there too that is specific to Leviatan Scans just in case it ends up being necessary again.

**Pull request merged**
